import { mkdir, writeFile } from "node:fs/promises";

const SPECIES_URL = "https://pokeapi.co/api/v2/pokemon-species?limit=2000";
const OFFICIAL_ARTWORK = (dexNo) =>
  `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${dexNo}.png`;

const toDexId = (dexNo) => String(dexNo).padStart(4, "0");

function pickName(names, language) {
  return names.find((entry) => entry.language.name === language)?.name || "";
}

function getIdFromUrl(url) {
  const match = String(url).match(/\/pokemon-species\/(\d+)\//);
  return match ? Number(match[1]) : null;
}

async function fetchJson(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Failed to fetch ${url}: ${response.status}`);
  return response.json();
}

function getMegaKey(pokemonName) {
  if (pokemonName.endsWith("-mega-x")) return "mega-x";
  if (pokemonName.endsWith("-mega-y")) return "mega-y";
  if (pokemonName.includes("-mega")) return "mega";
  return null;
}

function getMegaSuffix(key) {
  if (key === "mega-x") return "X";
  if (key === "mega-y") return "Y";
  return "";
}

async function mapConcurrent(items, limit, mapper) {
  const results = new Array(items.length);
  let nextIndex = 0;

  await Promise.all(
    Array.from({ length: limit }, async () => {
      while (nextIndex < items.length) {
        const index = nextIndex;
        nextIndex += 1;
        results[index] = await mapper(items[index], index);
      }
    })
  );

  return results;
}

const speciesList = await fetchJson(SPECIES_URL);
const speciesRefs = speciesList.results
  .map((entry) => ({ ...entry, dexNo: getIdFromUrl(entry.url) }))
  .filter((entry) => Number.isInteger(entry.dexNo))
  .sort((a, b) => a.dexNo - b.dexNo);

const speciesPayloads = await mapConcurrent(speciesRefs, 12, async (entry) => {
  const [species, pokemon] = await Promise.all([
    fetchJson(entry.url),
    fetchJson(`https://pokeapi.co/api/v2/pokemon/${entry.dexNo}`),
  ]);

  const speed = pokemon.stats.find((stat) => stat.stat.name === "speed")?.base_stat;
  if (!Number.isFinite(speed)) return null;

  const englishName = pickName(species.names, "en") || pokemon.name;
  const koreanName = pickName(species.names, "ko") || englishName;
  const japaneseName = pickName(species.names, "ja-Hrkt") || pickName(species.names, "ja") || englishName;

  const baseEntry = {
    id: `nat-${toDexId(entry.dexNo)}`,
    dexNo: entry.dexNo,
    formKey: "base",
    displayName: koreanName,
    displayNameEn: englishName,
    displayNameJa: japaneseName,
    speed,
    icon: OFFICIAL_ARTWORK(entry.dexNo),
  };

  const megaVarieties = species.varieties.filter((variety) => getMegaKey(variety.pokemon.name));
  const megaOptions = await mapConcurrent(megaVarieties, 4, async (variety) => {
    const key = getMegaKey(variety.pokemon.name);
    const suffix = getMegaSuffix(key);
    const megaPokemon = await fetchJson(variety.pokemon.url);
    const megaSpeed = megaPokemon.stats.find((stat) => stat.stat.name === "speed")?.base_stat;
    if (!Number.isFinite(megaSpeed)) return null;

    return {
      key,
      label: `메가${koreanName}${suffix}`,
      labelEn: `Mega ${englishName}${suffix ? ` ${suffix}` : ""}`,
      labelJa: `メガ${japaneseName}${suffix}`,
      speed: megaSpeed,
      icon: OFFICIAL_ARTWORK(megaPokemon.id),
    };
  });

  return {
    entry: baseEntry,
    megaOptions: megaOptions.filter(Boolean),
  };
});

const roster = speciesPayloads.map((payload) => payload?.entry).filter(Boolean);
const allMegaOptionsByName = Object.fromEntries(
  speciesPayloads
    .filter((payload) => payload?.entry && payload.megaOptions.length > 0)
    .map((payload) => [payload.entry.displayName, payload.megaOptions])
);
const content = `// Generated by scripts/generateAllPokemonRoster.mjs.
// Base species plus official Mega Evolution options.

export const allPokemonRoster = ${JSON.stringify(roster, null, 2)};

export const allMegaOptionsByName = ${JSON.stringify(allMegaOptionsByName, null, 2)};
`;

await mkdir("src/data", { recursive: true });
await writeFile("src/data/allPokemonRoster.js", content, "utf8");

console.log(`Generated ${roster.length} Pokemon entries and ${Object.keys(allMegaOptionsByName).length} Mega-capable species.`);
